#!/usr/bin/env node
// ============================================================
// generate-seed.js
// Generates seed.sql with bcrypt-hashed passwords (cost 12).
//
// Usage:
//   node generate-seed.js            → writes seed.sql in same dir
//   node generate-seed.js --stdout   → prints to terminal
// ============================================================

const bcrypt = require('bcryptjs');
const fs = require('fs');
const path = require('path');

// ── Password hashes ──────────────────────────────────────────
const COST = 12;
const hodHash = bcrypt.hashSync('hod123', COST);
const staffHash = bcrypt.hashSync('staff123', COST);
const studentHash = bcrypt.hashSync('student123', COST);

// ── Helper ───────────────────────────────────────────────────
const esc = (s) => s.replace(/'/g, "''");      // SQL string escape
const ts = '2026-03-01 09:00:00';              // base timestamp

// ── Build SQL ────────────────────────────────────────────────
const sql = `-- ============================================================
-- College LMS — Seed Data
-- Auto-generated by generate-seed.js on ${new Date().toISOString()}
-- Passwords hashed with bcrypt cost factor ${COST}
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- 1. USERS  (1 HOD + 3 Staff + 10 Students = 14 users)
-- ────────────────────────────────────────────────────────────

-- HOD  (id = 1)
INSERT INTO users (username, email, password_hash, role, full_name, phone, is_active)
VALUES ('hod', 'hod@college.edu', '${esc(hodHash)}', 'hod', 'Dr. Ramesh Kumar', '9000000001', true);

-- Staff (ids = 2, 3, 4)
INSERT INTO users (username, email, password_hash, role, full_name, phone, is_active) VALUES
  ('staff1', 'staff1@college.edu', '${esc(staffHash)}', 'staff', 'Prof. Anil Sharma',    '9000000002', true),
  ('staff2', 'staff2@college.edu', '${esc(staffHash)}', 'staff', 'Prof. Priya Menon',     '9000000003', true),
  ('staff3', 'staff3@college.edu', '${esc(staffHash)}', 'staff', 'Prof. Suresh Reddy',    '9000000004', true);

-- Students (ids = 5 … 14)
INSERT INTO users (username, email, password_hash, role, full_name, phone, is_active) VALUES
  ('student1',  'student1@college.edu',  '${esc(studentHash)}', 'student', 'Aarav Patel',        '9100000001', true),
  ('student2',  'student2@college.edu',  '${esc(studentHash)}', 'student', 'Vivaan Singh',       '9100000002', true),
  ('student3',  'student3@college.edu',  '${esc(studentHash)}', 'student', 'Ananya Iyer',        '9100000003', true),
  ('student4',  'student4@college.edu',  '${esc(studentHash)}', 'student', 'Diya Nair',          '9100000004', true),
  ('student5',  'student5@college.edu',  '${esc(studentHash)}', 'student', 'Ishaan Gupta',       '9100000005', true),
  ('student6',  'student6@college.edu',  '${esc(studentHash)}', 'student', 'Kavya Desai',        '9100000006', true),
  ('student7',  'student7@college.edu',  '${esc(studentHash)}', 'student', 'Rohan Joshi',        '9100000007', true),
  ('student8',  'student8@college.edu',  '${esc(studentHash)}', 'student', 'Meera Rao',          '9100000008', true),
  ('student9',  'student9@college.edu',  '${esc(studentHash)}', 'student', 'Arjun Verma',        '9100000009', true),
  ('student10', 'student10@college.edu', '${esc(studentHash)}', 'student', 'Sneha Kulkarni',     '9100000010', true);

-- ────────────────────────────────────────────────────────────
-- 2. DEPARTMENTS
-- ────────────────────────────────────────────────────────────
INSERT INTO departments (name, code, hod_id)
VALUES ('Computer Science Engineering', 'CSE', 1);

-- Link all users to department 1
UPDATE users SET department_id = 1;

-- ────────────────────────────────────────────────────────────
-- 3. SUBJECTS  (4 subjects, assigned to staff)
-- ────────────────────────────────────────────────────────────
INSERT INTO subjects (name, code, semester, academic_year, department_id, staff_id, is_active) VALUES
  ('Mathematics',  'MAT101', 1, '2025-2026', 1, 2, true),   -- id=1  → staff1
  ('Physics',      'PHY101', 1, '2025-2026', 1, 3, true),   -- id=2  → staff2
  ('Chemistry',    'CHE101', 1, '2025-2026', 1, 4, true),   -- id=3  → staff3
  ('Programming',  'CSE101', 1, '2025-2026', 1, 2, true);   -- id=4  → staff1

-- ────────────────────────────────────────────────────────────
-- 4. STUDENT PROFILES
-- ────────────────────────────────────────────────────────────
INSERT INTO student_profiles (user_id, roll_number, batch, year_of_study, phone, parent_phone) VALUES
  (5,  'CSE2025001', '2025', 1, '9100000001', '9200000001'),
  (6,  'CSE2025002', '2025', 1, '9100000002', '9200000002'),
  (7,  'CSE2025003', '2025', 1, '9100000003', '9200000003'),
  (8,  'CSE2025004', '2025', 1, '9100000004', '9200000004'),
  (9,  'CSE2025005', '2025', 1, '9100000005', '9200000005'),
  (10, 'CSE2025006', '2025', 1, '9100000006', '9200000006'),
  (11, 'CSE2025007', '2025', 1, '9100000007', '9200000007'),
  (12, 'CSE2025008', '2025', 1, '9100000008', '9200000008'),
  (13, 'CSE2025009', '2025', 1, '9100000009', '9200000009'),
  (14, 'CSE2025010', '2025', 1, '9100000010', '9200000010');

-- ────────────────────────────────────────────────────────────
-- 5. STAFF PROFILES
-- ────────────────────────────────────────────────────────────
INSERT INTO staff_profiles (user_id, employee_id, designation, phone) VALUES
  (1, 'EMP001', 'Head of Department',    '9000000001'),
  (2, 'EMP002', 'Assistant Professor',   '9000000002'),
  (3, 'EMP003', 'Associate Professor',   '9000000003'),
  (4, 'EMP004', 'Assistant Professor',   '9000000004');

-- ────────────────────────────────────────────────────────────
-- 6. SUBJECT ENROLLMENTS  (all 10 students × 4 subjects = 40)
-- ────────────────────────────────────────────────────────────
INSERT INTO subject_enrollments (subject_id, student_id) VALUES
  -- Mathematics
  (1,5),(1,6),(1,7),(1,8),(1,9),(1,10),(1,11),(1,12),(1,13),(1,14),
  -- Physics
  (2,5),(2,6),(2,7),(2,8),(2,9),(2,10),(2,11),(2,12),(2,13),(2,14),
  -- Chemistry
  (3,5),(3,6),(3,7),(3,8),(3,9),(3,10),(3,11),(3,12),(3,13),(3,14),
  -- Programming
  (4,5),(4,6),(4,7),(4,8),(4,9),(4,10),(4,11),(4,12),(4,13),(4,14);

-- ────────────────────────────────────────────────────────────
-- 7. ATTENDANCE SESSIONS  (5 sessions)
-- ────────────────────────────────────────────────────────────
INSERT INTO attendance_sessions (subject_id, staff_id, session_date, session_type) VALUES
  (1, 2, '2026-02-24', 'lecture'),    -- id=1  Mathematics
  (1, 2, '2026-02-25', 'lecture'),    -- id=2  Mathematics
  (2, 3, '2026-02-24', 'lecture'),    -- id=3  Physics
  (3, 4, '2026-02-26', 'lab'),        -- id=4  Chemistry
  (4, 2, '2026-02-27', 'lecture');    -- id=5  Programming

-- ────────────────────────────────────────────────────────────
-- 8. ATTENDANCE RECORDS  (for sessions 1-5, all 10 students)
-- ────────────────────────────────────────────────────────────

-- Session 1 — Mathematics 24 Feb
INSERT INTO attendance_records (session_id, student_id, status) VALUES
  (1,5,'present'),(1,6,'present'),(1,7,'absent'),(1,8,'present'),(1,9,'late'),
  (1,10,'present'),(1,11,'present'),(1,12,'absent'),(1,13,'present'),(1,14,'present');

-- Session 2 — Mathematics 25 Feb
INSERT INTO attendance_records (session_id, student_id, status) VALUES
  (2,5,'present'),(2,6,'present'),(2,7,'present'),(2,8,'present'),(2,9,'present'),
  (2,10,'absent'),(2,11,'present'),(2,12,'present'),(2,13,'late'),(2,14,'present');

-- Session 3 — Physics 24 Feb
INSERT INTO attendance_records (session_id, student_id, status) VALUES
  (3,5,'present'),(3,6,'absent'),(3,7,'present'),(3,8,'late'),(3,9,'present'),
  (3,10,'present'),(3,11,'present'),(3,12,'present'),(3,13,'present'),(3,14,'absent');

-- Session 4 — Chemistry 26 Feb (lab)
INSERT INTO attendance_records (session_id, student_id, status) VALUES
  (4,5,'present'),(4,6,'present'),(4,7,'present'),(4,8,'present'),(4,9,'present'),
  (4,10,'present'),(4,11,'absent'),(4,12,'present'),(4,13,'present'),(4,14,'present');

-- Session 5 — Programming 27 Feb
INSERT INTO attendance_records (session_id, student_id, status) VALUES
  (5,5,'present'),(5,6,'present'),(5,7,'present'),(5,8,'absent'),(5,9,'present'),
  (5,10,'present'),(5,11,'present'),(5,12,'present'),(5,13,'present'),(5,14,'late');

-- ────────────────────────────────────────────────────────────
-- 9. ASSIGNMENTS  (2 per subject = 8 total)
-- ────────────────────────────────────────────────────────────
INSERT INTO assignments (subject_id, title, description, due_date, max_marks, allowed_file_types, created_by, is_active) VALUES
  (1, 'Linear Algebra Problem Set',   'Solve problems on matrices and determinants.',           '2026-03-10 23:59:00', 25, 'pdf,doc', 2, true),
  (1, 'Calculus Assignment',          'Derivatives and integrals practice.',                    '2026-03-15 23:59:00', 25, 'pdf,doc', 2, true),
  (2, 'Newton''s Laws Worksheet',     'Solve 20 problems on Newton''s three laws of motion.',   '2026-03-12 23:59:00', 20, 'pdf',     3, true),
  (2, 'Wave Optics Lab Report',       'Write a detailed lab report on the diffraction experiment.', '2026-03-18 23:59:00', 30, 'pdf,doc', 3, true),
  (3, 'Chemical Bonding Questions',   'Answer questions on ionic and covalent bonding.',        '2026-03-11 23:59:00', 20, 'pdf',     4, true),
  (3, 'Organic Chemistry Structures', 'Draw and name 15 organic molecules.',                    '2026-03-20 23:59:00', 25, 'pdf,doc', 4, true),
  (4, 'Python Basics',                'Write 10 Python programs on loops and conditions.',      '2026-03-13 23:59:00', 30, 'pdf,py,zip', 2, true),
  (4, 'Data Structures Assignment',   'Implement stack and queue in C.',                        '2026-03-22 23:59:00', 30, 'pdf,c,zip',  2, true);

-- ────────────────────────────────────────────────────────────
-- 10. ASSIGNMENT SUBMISSIONS  (sample: first 3 students for assignments 1 & 3)
-- ────────────────────────────────────────────────────────────
INSERT INTO assignment_submissions (assignment_id, student_id, file_url, submitted_at, marks_obtained, feedback, graded_by, graded_at, is_late) VALUES
  (1, 5, '/uploads/submissions/stu5_a1.pdf', '2026-03-09 18:30:00', 22.5, 'Excellent work!', 2, '2026-03-11 10:00:00', false),
  (1, 6, '/uploads/submissions/stu6_a1.pdf', '2026-03-10 22:15:00', 18.0, 'Good, but review question 5.', 2, '2026-03-11 10:10:00', false),
  (1, 7, '/uploads/submissions/stu7_a1.pdf', '2026-03-11 02:00:00', 15.0, 'Submitted late. Partial marks.', 2, '2026-03-11 10:20:00', true),
  (3, 5, '/uploads/submissions/stu5_a3.pdf', '2026-03-11 16:00:00', 19.0, 'Very well done.', 3, '2026-03-13 09:00:00', false),
  (3, 6, '/uploads/submissions/stu6_a3.pdf', '2026-03-12 20:00:00', 16.0, 'Needs clarity on 3rd law problems.', 3, '2026-03-13 09:15:00', false);

-- ────────────────────────────────────────────────────────────
-- 11. ASSESSMENTS  (1 per subject = 4)
-- ────────────────────────────────────────────────────────────
INSERT INTO assessments (subject_id, name, max_marks, assessment_type, conducted_date, created_by) VALUES
  (1, 'Mathematics Internal Test 1',  50, 'internal',  '2026-02-28', 2),
  (2, 'Physics Midterm',              50, 'midterm',   '2026-02-28', 3),
  (3, 'Chemistry Practical Exam',     30, 'practical', '2026-03-01', 4),
  (4, 'Programming Viva',             20, 'viva',      '2026-03-02', 2);

-- ────────────────────────────────────────────────────────────
-- 12. ASSESSMENT MARKS  (first 5 students for each assessment)
-- ────────────────────────────────────────────────────────────
INSERT INTO assessment_marks (assessment_id, student_id, marks_obtained, is_published, entered_by) VALUES
  -- Mathematics Internal
  (1, 5,  42.0, true, 2), (1, 6,  38.5, true, 2), (1, 7,  29.0, true, 2), (1, 8,  45.0, true, 2), (1, 9,  33.5, true, 2),
  -- Physics Midterm
  (2, 5,  40.0, true, 3), (2, 6,  35.0, true, 3), (2, 7,  28.0, true, 3), (2, 8,  44.0, true, 3), (2, 9,  31.0, true, 3),
  -- Chemistry Practical
  (3, 5,  27.0, true, 4), (3, 6,  22.5, true, 4), (3, 7,  18.0, true, 4), (3, 8,  29.0, true, 4), (3, 9,  24.0, true, 4),
  -- Programming Viva
  (4, 5,  18.0, true, 2), (4, 6,  15.0, true, 2), (4, 7,  12.0, true, 2), (4, 8,  19.0, true, 2), (4, 9,  16.0, true, 2);

-- ────────────────────────────────────────────────────────────
-- 13. COURSE CONTENT  (sample materials)
-- ────────────────────────────────────────────────────────────
INSERT INTO course_content (subject_id, title, description, content_type, file_url, week_number, topic, uploaded_by, is_visible) VALUES
  (1, 'Introduction to Matrices',        'Basics of matrices and types.',                  'pdf',   '/uploads/content/mat_ch1.pdf',    1, 'Matrices',          2, true),
  (1, 'Determinants — Video Lecture',     'Video explaining determinants in detail.',       'video', 'https://youtu.be/example1',       2, 'Determinants',      2, true),
  (2, 'Newton''s Laws PPT',              'Presentation covering all three laws.',          'ppt',   '/uploads/content/phy_ch1.pptx',   1, 'Mechanics',         3, true),
  (3, 'Chemical Bonding Notes',           'Detailed notes on ionic and covalent bonds.',   'pdf',   '/uploads/content/che_ch1.pdf',    1, 'Chemical Bonding',  4, true),
  (4, 'Python Programming Handbook',      'Complete guide for beginners.',                 'doc',   '/uploads/content/cse_python.docx', 1, 'Python Basics',     2, true),
  (4, 'LeetCode Practice Problems',       'Curated list of beginner-level coding problems.','link', 'https://leetcode.com/problemset', 3, 'Problem Solving',   2, true);

-- ────────────────────────────────────────────────────────────
-- 14. ANNOUNCEMENTS
-- ────────────────────────────────────────────────────────────
INSERT INTO announcements (title, body, target_audience, posted_by, subject_id, department_id, is_pinned, send_email) VALUES
  ('Welcome to Semester 1!',
   'Welcome to the CSE department. Please complete your enrollment formalities by March 10.',
   'all', 1, NULL, 1, true, true),
  ('Mathematics Test 1 Results Published',
   'The results for Internal Test 1 have been published. Check your marks on the portal.',
   'students', 2, 1, 1, false, false),
  ('Faculty Meeting on March 15',
   'All faculty members are requested to attend the department meeting at 3 PM in Room 201.',
   'staff', 1, NULL, 1, true, false),
  ('Physics Lab Schedule Update',
   'The Physics lab sessions have been rescheduled to Thursday 2-5 PM starting next week.',
   'all', 3, 2, 1, false, true),
  ('Submit Programming Assignment by March 13',
   'Reminder: The Python Basics assignment is due on March 13. Late submissions will lose marks.',
   'students', 2, 4, 1, false, false);

-- ────────────────────────────────────────────────────────────
-- 15. LEAVE REQUESTS  (sample)
-- ────────────────────────────────────────────────────────────
INSERT INTO leave_requests (staff_id, leave_type, start_date, end_date, reason, status, reviewed_by, review_comment, reviewed_at) VALUES
  (2, 'casual',  '2026-03-05', '2026-03-06', 'Personal work.',                      'approved', 1, 'Approved. Please arrange substitute.', '2026-03-04 11:00:00'),
  (3, 'medical', '2026-03-10', '2026-03-12', 'Medical appointment and recovery.',    'pending',  NULL, NULL, NULL),
  (4, 'duty',    '2026-03-08', '2026-03-08', 'Attending inter-college tech fest.',    'approved', 1, 'Granted.',                             '2026-03-07 09:00:00');


-- ============================================================
-- Seed complete!
-- ============================================================
`;

// ── Write or print ───────────────────────────────────────────
const outPath = path.join(__dirname, 'seed.sql');

if (process.argv.includes('--stdout')) {
    process.stdout.write(sql);
} else {
    fs.writeFileSync(outPath, sql, 'utf8');
    console.log(`✅ seed.sql written to ${outPath}`);
    console.log(`   HOD password:     hod123     → ${hodHash}`);
    console.log(`   Staff password:   staff123   → ${staffHash}`);
    console.log(`   Student password: student123 → ${studentHash}`);
}
